version: '3.8'

services:
  postgres-manufacturing:
    image: postgres:16
    environment:
      POSTGRES_DB: manufacturing
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - ./manufacturing/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-retail:
    image: postgres:16
    environment:
      POSTGRES_DB: retail
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"
    volumes:
      - ./retail/init.sql:/docker-entrypoint-initdb.d/init.sql

